#!/bin/bash

beep='paplay /usr/share/sounds/ubuntu/stereo/message-new-instant.ogg'
battery='upower -i /org/freedesktop/UPower/devices/battery_BAT0| grep -E "state|to\ empty|percentage"'

state() {
	echo $(eval $battery | grep state | awk '{print $2}')
}

recheck() {
	if [ ! $(state) == "discharging" ]; then exit; fi
}

# This gets the integer percentage of current battery capacity
p=$(eval $battery | grep 'percentage' | awk '{print $2}' | awk -F '%' '{print $1}')

run_beep() {
	for i in {10..0} ; do
		for j in {0..3} ; do
			eval $beep&
			k=$i
			while [ "$k" -gt 0 ] ; do
				sleep 0.05;
				k=$(( k - 1 ))
			done;
		done;
		recheck;
	done;

	for i in {0..3}; do
		eval $beep
		recheck;
	done
}

if [ "$p" -le 15 -a $(state) == "discharging" ] ; then
	run_beep&
	sleep 30;

	recheck;
	sudo pm-hibernate;
fi