#!/bin/bash

COURSES_FOLDER="/mnt/Storage/Videos/Courses"
COURSES_LIST_FILE="${COURSES_FOLDER}/coursera-download-list.txt"

cd "${COURSES_FOLDER}"

mapfile -t courses < "${COURSES_LIST_FILE}"

for course in "${courses[@]}"; do
	if echo "${course}" | grep -v '^\s*#' | grep -q '\S'; then
		echo "Downloading ${course} into ${COURSES_FOLDER}/${course}"
		coursera-dl --disable-url-skipping --resume --path "${COURSES_FOLDER}" -sl en "${course}" -n
	fi
done
