#!/bin/sh

set -e

DOTFILES_HOME="$(realpath "$(dirname "$0")")"
TMP_HOME="$DOTFILES_HOME/data/tmp_home"

RESTORE_DOTFILES_CONFIG=false
DOTFILES_CONFIG_PATH="$DOTFILES_HOME/data/dotfiles_config"

clean () {
    rm -vrf "$TMP_HOME"
}

install () {
    if [ -f "$DOTFILES_CONFIG_PATH" ]; then
        cp "$DOTFILES_CONFIG_PATH" "${DOTFILES_CONFIG_PATH}.bak"
        RESTORE_DOTFILES_CONFIG=true
    fi

    mkdir -pv "$TMP_HOME"
    cd "$TMP_HOME"

    "$DOTFILES_HOME/install" --no-interactive --user-home "$TMP_HOME" --dotfiles-path "$DOTFILES_HOME"
}

start () {
    HOME="$TMP_HOME" "$SHELL"
}

if [ -e "$TMP_HOME" ]; then
    printf "Another temp home exitsts. Clean (y/[n])? "
    read -r response
    if [ "$response" = 'y' ]; then
        clean
        install
    else
        printf "Reinstall to $TMP_HOME (y/[n])? "
        read -r response
        if [ "$response" = 'y' ]; then
            install
        fi
    fi
else
    install
fi

set +e

echo "You can try my dotfiles in this shell."
start

if [ "$RESTORE_DOTFILES_CONFIG" = 'true' ]; then
    mv "${DOTFILES_CONFIG_PATH}.bak" "${DOTFILES_CONFIG_PATH}"
fi
