#!/usr/bin/env python

import sys


PROJECT_HOME = '/mnt/Storage/Lab/Java/javaProject'

def main(argv):
	if len(argv) < 2:
		print('Enter url: ', end='')
		url = input()
	else:
		url = argv[1]

	problem_name = url.split('?')[0].split('/')[-1]
	class_name = problem_name.split('-')
	class_name = ''.join(i.capitalize() for i in class_name)
	if class_name[0].isdigit():
		class_name = '_' + class_name
	class_name = ''.join((c if (c.isalpha() or c.isdigit()) else '_') for c in class_name )
	input_file = open(PROJECT_HOME + '/Contests/Template.java')
	file = ''.join(input_file.readlines())
	input_file.close

	file = file.replace('Template', class_name)
	output_filename = PROJECT_HOME + '/src/{0}.java'.format(class_name)
	output_file = open(output_filename, 'w')
	output_file.write(file)
	output_file.flush()
	output_file.close()
	print('Created file: ' + output_filename)
	
	
if __name__ == '__main__':
	main(sys.argv)
