#!/bin/sh

set -e

if [ -f "~/.dotfiles_config" ]; then
    . "~/.dotfiles_config"
fi

# Set MY_HOME
MY_HOME="$HOME"
printf "Enter your home directory [%s]: " "$MY_HOME"
read -r response
if [ ! -z "$response" ]; then
    MY_HOME="$(realpath "$response")"
fi

# Set DOTFILES_HOME
DOTFILES_HOME="$(realpath .)"
printf "Enter dofiles directory [%s]: " "$DOTFILES_HOME"
read -r response
if [ ! -z "$response" ]; then
    DOTFILES_HOME="$(realpath "$response")"
fi

DOTFILES_DIR="$MY_HOME/.dotfiles"
if [ ! -d "$DOTFILES_DIR" ]; then
    if [ -e "$DOTFILES_DIR" ]; then
        mv "$DOTFILES_DIR" "${DOTFILES_DIR}.bak.$(date +%s)"
    fi
    ln -sf "$DOTFILES_HOME" "$DOTFILES_DIR"
    DOTFILES_HOME="$DOTFILES_DIR"
fi

DOTFILES_DATA_DIR="$DOTFILES_HOME/data"
mkdir -pv "$DOTFILES_DATA_DIR"
mkdir -pv "$DOTFILES_DATA_DIR/history"
touch "$DOTFILES_DATA_DIR/history/zsh_history"

DOTFILES_CONFIG_FILE="$DOTFILES_DATA_DIR/dotfiles_config"


safe_link() {
    from="$1"
    to="$2"
    printf "Link %s -> %s ? ([y]/n) " "$from" "$to"
    read -r response

    if [ "$response" != 'n' ]; then
        if [ -e "$from" ]; then
            echo mv "$from" "${from}.bak.$(date +%s)"
            mv "$from" "${from}.bak.$(date +%s)"
        fi

        dir="$(dirname "$from")"
        if [ ! -d "$dir" ]; then
            mkdir -pv "$dir"
        fi

        ln -sf "$to" "$from"
    fi
}

config_files="
    driverc
    gitconfig
    gitignore
    inputrc
    irbrc
    sqliterc
    tmux.conf
    vim
    wgetrc
"

for cf in $config_files; do
    safe_link ~/."$cf" "$DOTFILES_HOME/config/$cf"
done

for cf in bashrc zshrc; do
    safe_link ~/."$cf" "$DOTFILES_HOME/config/shellrc"
done

for cf in netrc trc; do
    safe_link ~/."$cf" "$DOTFILES_HOME/config/secret/$cf"
done

safe_link ~/.dotfiles_config "$DOTFILES_CONFIG_FILE"
safe_link "$DOTFILES_HOME/thirdparty/oh-my-zsh/custom/themes/n1amr.zsh-theme" ../../../../config/n1amr.zsh-theme
safe_link ~/".ipython/profile_default" "$DOTFILES_HOME/config/ipython/profile_default"
safe_link ~/.zsh_history.bak "$DOTFILES_DATA_DIR/history/zsh_history"
safe_link ~/.vimrc "$DOTFILES_HOME/config/vim/vimrc"
safe_link ~/.config/ranger/rc.conf "$DOTFILES_HOME/config/ranger/rc.conf"
safe_link ~/.config/ranger/rifle.conf "$DOTFILES_HOME/config/ranger/rifle.conf"

cat >> "$DOTFILES_CONFIG_FILE" <<EOF
#!/bin/bash

export MY_HOME='$MY_HOME'
export DOTFILES_HOME='$DOTFILES_HOME'
export PYENV_ROOT='$MY_HOME/.pyenv'
export RBENV_ROOT='$MY_HOME/.rbenv'
EOF

chmod +x "$DOTFILES_CONFIG_FILE"

echo "Contents of config file at $DOTFILES_CONFIG_FILE:"
echo "===== Start ====="
cat "$DOTFILES_CONFIG_FILE"
echo "===== End ====="

# fzf install
"$DOTFILES_HOME/thirdparty/fzf/install"

echo "Successful!"
exec "$SHELL"
