#!/bin/bash

includes="$MY_SCRIPTS_ROOT/config/sync.rc/emergency"
destination='/mnt/Storage/Backups/emergency'

while IFS= read -r line; do
    echo $line
    rsync -k -av --delete --relative -b --backup-dir="$destination/trash" "$line" "$destination" --exclude-from="$MY_SCRIPTS_ROOT/config/sync.rc/emergency-excludes"
done < "$includes"
