#!/bin/bash

VPN_HOME='/mnt/Storage/Shared/vpnbook/'

vpnconnections=(ca1.vpnbook.com\
	de233.vpnbook.com\
	euro214.vpnbook.com\
	euro217.vpnbook.com\
	us1.vpnbook.com\
	us2.vpnbook.com\
)

mkdir -p "$VPN_HOME"/credentials
cd "$VPN_HOME"/credentials
credentials_filename='current'

# Initialiaze options
no_prompt="false"

# Read options
for i in "$@"; do
	case $i in
	--no-prompt)
		no_prompt="true"
	;;
	esac
done

echo -e "Trying to update vpn credentials..."

echo "Fetching from http://www.vpnbook.com/freevpn"
cred=$(wget http://www.vpnbook.com/freevpn -qO - | grep -Po '(Password|Username)[^\r\n]*' | grep -Po '(?<=>)\w+?(?=<)' | head -2)
if [[ -z "$cred" ]]; then
	echo "Fetching from https://twitter.com/vpnbook"
	cred=$(/home/n1amr/.rbenv/shims/t timeline vpnbook | head -2 | tail -1 | grep -Po 'Username.*' | sed 's/ /\n/g' | grep -Pv ':')
fi

[[ -n "$cred" ]] && echo "$cred" > credentials.tmp && successful='true'
if [ x"$successful" != x'true' ]; then
	echo Cannot retrieve data!
	rm -f credentials.tmp
	exit
fi

echo -e "\nNew credenatials:" &&
cat credentials.tmp &&
echo

# Prompt before modifying
if [ x"$no_prompt" == x"false" ]; then
	echo -en "Save? [y/n] " &&
	read response
	if [ x"$response" != x"y" ]; then exit; fi
fi

# Update history
if [ ! -d backup ]; then mkdir backup; fi
if [ -f "$credentials_filename" ];then mv "$credentials_filename" "backup/$(date +'%F-%T')"; fi
mv credentials.tmp "$credentials_filename"
echo "Saved to $(realpath \"$credentials_filename\")"

# Update credentials in vpn connections
new_password=$(cat "$credentials_filename" | tail -1)
for v in "${vpnconnections[@]}"; do
	nmcli connection modify "$v" vpn.secrets "password = $new_password" &&
	echo "Updated $v successfully"
done
