#!/bin/bash

N1AMR_HOME="/home/n1amr"
GOPATH="$N1AMR_HOME/.gopath"
PATH="$GOPATH/bin:$PATH"

DRIVE_PATH="/mnt/Storage/GoogleDrive"

current_month_folder=$(date +'%Y/%m')
last_month_folder=$(date --date="-1 month" +'%Y/%m')
# last_month_folder=$(date --date="$(date +%Y-%m-15) -1 month" +'%Y/%m')

auto_pull_folders=(
	"ASU/CSE 2017  2nd term 3rd year"
	"ASU/Lab/CSE 351 Electrical Testing -2"
	"Google Photos/${current_month_folder}"
	"Google Photos/${last_month_folder}"
	"IFTTT"
)

auto_push_folders=(
	"ASU/Study/Second Term/"
	"Personal"
	# "Backups/Internet/Twitter Favorites Archive"
)

echo -e "$(date)\n"

# Options init
no_prompt=false
exclude=true

# Set Options
while [[ $# > 0 ]]; do
	case "$1" in
		-p|--no-prompt)
			no_prompt=true
		;;
		-f|--no-exclude)
			exclude=false
		;;
		-o|--drive-options)
			drive_options="$2"
			shift;
		;;
		*)
			echo Error: Unknown argument \"$1\"
			exit 1
		;;
	esac
	shift
done

# Set flags
COMMONFLAGS="$drive_options"
PUSHFLAGS='-no-clobber'

if [ "$no_prompt" == "true" ]; then
	COMMONFLAGS="$COMMONFLAGS -no-prompt"
fi

if [ "$exclude" == "true" ]; then
	COMMONFLAGS="$COMMONFLAGS -exclude-ops=delete,update"
fi

# Pull all
for f in "${auto_pull_folders[@]}"; do
	echo -e "\nPulling \"${f}\" ..."
	if [ -d "$DRIVE_PATH/${f}" ]; then
		cd "$DRIVE_PATH/${f}";
		drive pull $COMMONFLAGS
	fi
done

# Push all
for f in "${auto_push_folders[@]}"; do
	echo -e "\nPushing \"${f}\" ..."
	if [ -d "$DRIVE_PATH/${f}" ]; then
		cd "$DRIVE_PATH/${f}";
		drive push $COMMONFLAGS $PUSHFLAGS
	fi
done

exit 0