#!/bin/bash

N1AMR_HOME="/home/n1amr"
GOPATH="$N1AMR_HOME/.gopath"
PATH="$GOPATH/bin:$PATH"

DRIVE_PATH="/mnt/Storage/GoogleDrive"

current_month_folder=$(date +'%Y/%m')
last_month_folder=$(date --date="-1 month" +'%Y/%m')
# last_month_folder=$(date --date="$(date +%Y-%m-15) -1 month" +'%Y/%m')

auto_pull_folders=(
	"ASU/CSE 2017  2nd term 3rd year"
	"ASU/Lab/CSE 351 Electrical Testing -2"
	"Google Photos/${current_month_folder}"
	"Google Photos/${last_month_folder}"
	"IFTTT"
)

auto_push_folders=(
	"ASU/Study/Second Term/"
	"Personal"
)

# "Backups/Internet/Twitter Favorites Archive"

echo "$(date)"
echo

for f in "${auto_pull_folders[@]}"
do
	echo -e "Updating \"${f}\" ..."
	cd "$DRIVE_PATH/${f}" && if [ "$1" == "prompt" ];
	then
		drive pull -ignore-name-clashes
	else
		drive pull -ignore-name-clashes -no-prompt --exclude-ops=delete,update
	fi
	echo
done

for f in "${auto_push_folders[@]}"
do
	echo -e "Updating \"${f}\" ..."
	cd "$DRIVE_PATH/${f}" && if [ "$1" == "prompt" ];
	then
		drive push -ignore-name-clashes -no-clobber
	else
		drive push -ignore-name-clashes -no-clobber -no-prompt --exclude-ops=delete,update
	fi
	echo
done
