#!/bin/bash

N1AMR_HOME="/home/n1amr"
GOPATH="$N1AMR_HOME/.gopath"
PATH="$GOPATH/bin:$PATH"

DRIVE_PATH="/mnt/Storage/GoogleDrive"

current_month_folder=$(date +'%Y/%m')
last_month_folder=$(date --date="-1 month" +'%Y/%m')
# last_month_folder=$(date --date="$(date +%Y-%m-15) -1 month" +'%Y/%m')

auto_pull_folders=(
	"ASU/CSE 2017  2nd term 3rd year"
	"ASU/Lab/CSE 351 Electrical Testing -2"
	"Google Photos/${current_month_folder}"
	"Google Photos/${last_month_folder}"
	"IFTTT"
)

auto_push_folders=(
	"ASU/Study/Second Term/"
	"Personal"
	"Backups/Internet/Twitter Favorites Archive"
)

echo -e "$(date)\n"

# COMMONFLAGS='-ignore-name-clashes'
COMMONFLAGS=''
PUSHFLAGS='-no-clobber'

if [ "$1" != "prompt" ]; then
	COMMONFLAGS="$COMMONFLAGS -no-prompt --exclude-ops=delete,update"
fi

for f in "${auto_pull_folders[@]}"; do
	echo -e "Pulling \"${f}\" ..."
	if [ -d "$DRIVE_PATH/${f}" ]; then
		cd "$DRIVE_PATH/${f}";
		drive pull $COMMONFLAGS
	fi
done

for f in "${auto_push_folders[@]}"; do
	echo -e "Pushing \"${f}\" ..."
	if [ -d "$DRIVE_PATH/${f}" ]; then
		cd "$DRIVE_PATH/${f}";
		drive push $COMMONFLAGS $PUSHFLAGS
	fi
done
