#!/bin/bash

DESTINATION_DIRECTORY="${GDRIVE}/uploads"

if [ ! -d "$DESTINATION_DIRECTORY" ]; then mkdir -pv "$DESTINATION_DIRECTORY"; fi

for file in "$@";
do
  echo $file;
  cp -r "$file" "$DESTINATION_DIRECTORY/";
  cd "$DESTINATION_DIRECTORY";
  drive push -ignore-name-clashes -no-prompt;
  echo ------------------------------
  echo '** 'Uploaded "$flle"
  drive url "$file"
  echo ------------------------------
done
