#!/bin/bash

VPN_HOME='/mnt/Storage/Shared/vpnbook'
credentials_file="$VPN_HOME/credentials/current"
profile="$VPN_HOME/profiles/$(cat $VPN_HOME/profiles/current)"

credentials_updater='/home/n1amr/.local/bin/updatevpn'

connect () {
	sudo openvpn --config "${profile}" --auth-user-pass "${credentials_file}";
}

connect && successful=1

if [ "$successful" != 1 ]; then
	echo "Connection failed!!!"
	echo -n "Update credentials? [y/n]: "
	read response;
	if [ x"$response" == x"y" ]; then "${credentials_updater}"; connect; fi
fi
