#!/bin/bash

YOUTUBE_DOWNLADER='/usr/local/bin/youtube-dl'
YOUTUBE_HOME='/mnt/Storage/Shared/youtube'
URLS_FILE="$YOUTUBE_HOME/youtube-download-list"
HISTORY_FILE="$YOUTUBE_HOME/history"
ARGS='-f 18'

download=true

while [[ $# > 0 ]]; do
	echo "$1" >> "$URLS_FILE"
	echo "Added $1"
	download=false
	shift
done

if $download ; then
	cd "$YOUTUBE_HOME"
	touch "$URLS_FILE"
	"$YOUTUBE_DOWNLADER" -a "$URLS_FILE" "$ARGS" &&
		cat "$URLS_FILE" >> "$HISTORY_FILE" &&
		echo '' > "$URLS_FILE"
fi
