#!/bin/bash

HOME=/home/n1amr
BOTS_ROOT=$HOME/.twitter-bots


for bot_root in "${BOTS_ROOT}"/bot-*; do
    if [[ -d "$bot_root" ]]; then
        date >> "$bot_root"/log
        $HOME/.pyenv/shims/pytbot "$bot_root" >> "$bot_root"/log 2>&1 &
        echo -e "\n\n" >> "$bot_root"/log
    fi
done
