#!/bin/bash

password_file="$(dirname "$0")/password"

if [[ ! -f "$password_file" ]]; then
    echo "Add password to '$password_file' file"
    exit 1
fi

password="$(cat "$password_file")"
if [ -f config ]; then
  cat config | sed "s/${password}/PASSWORD/g" > config.template
else
  echo "config is not found"
  exit 1
fi
