execute pathogen#infect()

color my-theme
" color dracula

set number
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
set smartindent
set pastetoggle=<F10>
set cursorline
set mouse=a
set ignorecase

noremap <c-s-up> :m-2<CR>
noremap <c-s-down> :m+<CR>

noremap <c-k> :m-2<CR>
noremap <c-j> :m+<CR>

nnoremap <C-O> O<Esc>
nnoremap <CR> o<Esc>

nnoremap <Space> i_<Esc>r

nnoremap <C-L> <Esc>
inoremap <C-L> <Esc>
vnoremap <C-L> <Esc>
onoremap <C-L> <Esc>

" tab indenting
nnoremap <TAB> >>
nnoremap <S-TAB> <<

" change cursor shape in different modes
if has("autocmd")
  au VimEnter,InsertLeave * silent execute '!echo -ne "\e[1 q"' | redraw!
  au InsertEnter,InsertChange *
    \ if v:insertmode == 'i' |
    \   silent execute '!echo -ne "\e[5 q"' | redraw! |
    \ elseif v:insertmode == 'r' |
    \   silent execute '!echo -ne "\e[3 q"' | redraw! |
    \ endif
  au VimLeave * silent execute '!echo -ne "\e[ q"' | redraw!
endif

" NERDTree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'

" Airline
let g:airline_powerline_fonts = 1
let g:airline_theme="powerlineish"
let g:airline#extensions#tabline#enabled = 1
set laststatus=2
