color my-theme
" color dracula

set number
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
set smartindent
set pastetoggle=<F10>
set cursorline
set mouse=a

noremap <c-s-up> :call feedkeys( line('.')==1 ? '' : 'ddkP' )<CR>
noremap <c-s-down> ddp

noremap <c-k> :call feedkeys( line('.')==1 ? '' : 'ddkP' )<CR>
noremap <c-j> ddp

nnoremap <C-O> O<Esc>
nnoremap <CR> o<Esc>

nnoremap <Space> i_<Esc>r

nnoremap <C-L> <Esc>
inoremap <C-L> <Esc>
vnoremap <C-L> <Esc>
onoremap <C-L> <Esc>

" tab indenting
nnoremap <TAB> >>
nnoremap <S-TAB> <<

" change cursor shape in different modes
if has("autocmd")
  au VimEnter,InsertLeave * silent execute '!echo -ne "\e[1 q"' | redraw!
  au InsertEnter,InsertChange *
    \ if v:insertmode == 'i' |
    \   silent execute '!echo -ne "\e[5 q"' | redraw! |
    \ elseif v:insertmode == 'r' |
    \   silent execute '!echo -ne "\e[3 q"' | redraw! |
    \ endif
  au VimLeave * silent execute '!echo -ne "\e[ q"' | redraw!
endif
