#!/bin/bash

source ~/.dotfiles.env
source "$DOTFILES_HOME/bin/lib/log"
PATH="$DOTFILES_HOME/bin:$PATH"

if ! ok-to-download; then
    info "Aborted! Current connection is not allowed to download"
    exit 1
fi

exec > >(tee -a "$DOTFILES_LOG_FILE") 2>&1

echo
date -Isec
echo "================================================================================"

sudo apt-get update
sudo apt-get upgrade -dy
sudo apt-get dist-upgrade -dy

echo
