#!/bin/bash

source ~/.dotfiles.env
source "$DOTFILES_HOME/bin/lib/log"
export PATH="$DOTFILES_HOME/bin:$PATH"

info "Started sync"
sudo "$DOTFILES_HOME/bin/syncf" "$*"
sync-emergency
info "Finished sync"
