#!/bin/bash

source ~/.dotfiles_config
DRIVE_PATH="/mnt/Storage/GoogleDrive"
LOG_FILE="${DRIVE_PATH}/../.drive-log"
UPDATE_SCRIPT="$DOTFILES_ROOT/bin/updatedrive"

"$UPDATE_SCRIPT" --no-prompt >> "${LOG_FILE}" 2>> "${LOG_FILE}"
