#!/bin/bash

source ~/.dotfiles_config
source "$DOTFILES_HOME/bin/utils/log"
export PATH="$DOTFILES_HOME/bin:$PATH"

if ! ok-to-download; then
    info "Aborted! Current connection is not allowed to download"
    exit 1
fi

DRIVE_PATH="$DOTFILES_CONFIG_GOOGLE_DRIVE_ROOT"
LOG_FILE="$DRIVE_PATH/../.drive-log"

updatedrive --no-prompt >> "${LOG_FILE}" 2>&1
