#!/bin/bash

source ~/.dotfiles_config
source "$DOTFILES_HOME/bin/utils/log"

if ! ok-to-download; then
    info "Aborted! Current connection is not allowed to download"
    exit 1
fi

DRIVE_PATH="$DOTFILES_CONFIG_GOOGLE_DRIVE_ROOT"
LOG_FILE="${DRIVE_PATH}/../.drive-log"
UPDATE_SCRIPT="$DOTFILES_HOME/bin/updatedrive"

"$UPDATE_SCRIPT" --no-prompt >> "${LOG_FILE}" 2>&1
