#!/bin/bash

source ~/.dotfiles_config
if [ -z "$DOTFILES_CONFIG_YOUTUBE_HOME" ]; then
    echo 'Cannot find youtube home directory'
    exit 1
fi

YOUTUBE_HOME="$DOTFILES_CONFIG_YOUTUBE_HOME"
YOUTUBE_WATCH_LATER_DOWNLOADER="$DOTFILES_ROOT/bin/youtube-dl-watch-later"
YOUTUBE_LIST_DOWNLADER="$DOTFILES_ROOT/bin/youtube-dl-list"
LOG_FILE="$YOUTUBE_HOME/download-log"

echo -e "\n====================\n" >> "$LOG_FILE" 2>&1
date >> "$LOG_FILE" 2>&1
echo -e "====================\n\n" >> "$LOG_FILE" 2>&1
$YOUTUBE_WATCH_LATER_DOWNLOADER >> "$LOG_FILE" 2>&1
$YOUTUBE_LIST_DOWNLADER >> "$LOG_FILE" 2>&1
