#!/bin/bash

source ~/.dotfiles_config
source "$DOTFILES_HOME/bin/utils/log"
export PATH="$DOTFILES_HOME/bin:$PATH"

if [ -z "$DOTFILES_CONFIG_YOUTUBE_HOME" ]; then
    echo 'Cannot find youtube home directory'
    exit 1
fi

if ! ok-to-download; then
    info "Aborted! Current connection is not allowed to download"
    exit 1
fi

YOUTUBE_HOME="$DOTFILES_CONFIG_YOUTUBE_HOME"
LOG_FILE="$YOUTUBE_HOME/.downloader/log"

exec >> "$LOG_FILE" 2>&1  # redirect output and error to log file

[ ! -d "$YOUTUBE_HOME/.downloader" ] && mkdir -pv "$YOUTUBE_HOME/.downloader"

echo -e "\n====================\n"
date
echo -e "====================\n\n"

youtube-dl-watch-later
youtube-dl-list
